server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway9527
  cloud:
    gateway:
      discovery:
        # 开启通过服务名找服务
        locator:
          enabled: true
      routes:
        - id: payment_routh
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
      # 表示将自己注册进eureka server中
    register-with-eureka: true
    # 是否从eureka server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
logging:
  level:
    root: warn
  file:
    path: D:/a.log
